### PR TITLE
Features/keyboard

### PR DESCRIPTION
**Pull request by DavidBetteridge**
I think it's better,  but might be subjective!

### CODE REVIEW

**Comment by pgillett** [comment]
I think what might work is to detach the input from the PacMan. Put in a 'JoystickDirection' that is attached to input. When you press a key, JoystickDirection is always updated with the new direction. In the game we can then try a ChangeDirection(JoystickDirection) on every tick. That way the move will get implemented as soon as it is able to.

**Comment by kevbite** [comment]
I'm not sure that would work as we discard directions if we're at a wall... unless we keep them directions until the next move too?

**Comment by kevbite** [comment]
@DavidBetteridge what's the diff between GetKeyState from user32 vs key down?

Reading docs all look same - https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate

**Comment by pgillett** [comment]
> I'm not sure that would work as we discard directions if we're at a wall... unless we keep them directions until the next move too?

Which is right, but currently the KeyPress is only triggering a single attempt to change on that tick, which is obviously missing the exact time slot needed to turn the corner. We're only partially getting away with it due to the keyboard auto-repeat firing the KeyPress again, but obviously fires once, pauses, then fires at regular intervals.

However thinking more of the hardware, once you press the key (eg. move the joystick) it stays there in that direction, until it's moved again, eg. a state, rather than an event. So this state needs actioning whenever it is valid, eg. when we hit the junction.

The JoystickDirection (or TryingToGoInDirection) would be a state on the Game, and the (single) Game.ChangeDirection event fired by the UI just updates the JoystickDirection. We can then call AttemptSetDirection(JoystickDirection) before moving PacMan, either every time, or just if JoystickDireciton != PacMan.Direction.

**Comment by pgillett** [comment]
@DavidBetteridge Just reading over the code. Am I right in understanding that it's triggering a ChangeDirection event during every pre-tick if a key is currently pressed?

**Pull request merged**
